import { useEffect, useRef } from 'react'

import { python } from '@codemirror/lang-python'
import {
  defaultHighlightStyle,
  syntaxHighlighting,
} from '@codemirror/language'
import { EditorState, RangeSetBuilder, StateEffect, StateField } from '@codemirror/state'
import {
  Decoration,
  EditorView,
  GutterMarker,
  gutter,
  lineNumbers,
} from '@codemirror/view'

import styles from './ProtocolCodeView.module.css'

import type { DecorationSet } from '@codemirror/view'
import type { CommandSourceLocation } from '../api/types'

interface HighlightSpec {
  startLine: number
  endLine: number
  kind: 'selected' | 'error'
}

const setHighlights = StateEffect.define<HighlightSpec[]>()

const SELECTED_LINE_CLASS = 'cm-protocolSelectedLine'
const ERROR_LINE_CLASS = 'cm-protocolErrorLine'

function buildHighlightDecorations(
  state: EditorState,
  specs: HighlightSpec[]
): DecorationSet {
  const classesByLine = new Map<number, string>()
  for (const spec of specs) {
    const cls =
      spec.kind === 'error' ? ERROR_LINE_CLASS : SELECTED_LINE_CLASS
    for (let lineNumber = spec.startLine; lineNumber <= spec.endLine; lineNumber++) {
      if (lineNumber < 1 || lineNumber > state.doc.lines) continue
      const existing = classesByLine.get(lineNumber)
      if (existing == null) {
        classesByLine.set(lineNumber, cls)
      } else if (!existing.includes(cls)) {
        classesByLine.set(lineNumber, `${existing} ${cls}`)
      }
    }
  }

  const builder = new RangeSetBuilder<Decoration>()
  const sortedLines = Array.from(classesByLine.keys()).sort((a, b) => a - b)
  for (const lineNumber of sortedLines) {
    const from = state.doc.line(lineNumber).from
    builder.add(
      from,
      from,
      Decoration.line({ class: classesByLine.get(lineNumber) ?? '' })
    )
  }
  return builder.finish()
}

const highlightField = StateField.define<DecorationSet>({
  create: () => Decoration.none,
  update(decorations, transaction) {
    let next = decorations.map(transaction.changes)
    for (const effect of transaction.effects) {
      if (effect.is(setHighlights)) {
        next = buildHighlightDecorations(transaction.state, effect.value)
      }
    }
    return next
  },
  provide: field => EditorView.decorations.from(field),
})

class CommandCountMarker extends GutterMarker {
  readonly count: number

  constructor(count: number) {
    super()
    this.count = count
  }

  eq(other: GutterMarker): boolean {
    return other instanceof CommandCountMarker && other.count === this.count
  }

  toDOM(): Node {
    const badge = document.createElement('span')
    badge.className = 'cm-commandCountBadge'
    badge.textContent = String(this.count)
    badge.title = `${this.count} steps generated by this line`
    return badge
  }
}

const codeViewTheme = EditorView.theme({
  '&': {
    height: '100%',
    fontSize: '12px',
    backgroundColor: '#ffffff',
  },
  '.cm-scroller': {
    overflow: 'auto',
    fontFamily: "'Reach Mono', Menlo, Consolas, 'Courier New', monospace",
    lineHeight: '1.5',
  },
  '.cm-gutters': {
    backgroundColor: '#f8f8f8',
    color: '#737578',
    border: 'none',
    cursor: 'pointer',
  },
  [`.${SELECTED_LINE_CLASS}`]: {
    backgroundColor: 'rgba(0, 108, 250, 0.14)',
  },
  [`.${ERROR_LINE_CLASS}`]: {
    backgroundColor: 'rgba(191, 0, 0, 0.14)',
  },
  '.cm-commandCountGutter': {
    minWidth: '24px',
  },
  '.cm-commandCountBadge': {
    display: 'inline-block',
    minWidth: '16px',
    padding: '0 4px',
    borderRadius: '8px',
    backgroundColor: '#e1e8f5',
    color: '#16212d',
    fontSize: '10px',
    textAlign: 'center',
  },
})

export interface ProtocolCodeViewProps {
  source: string
  /** Statement range of the currently selected step, if it maps to source. */
  selectedLocation?: CommandSourceLocation | null
  /** Statement range to mark as the failure site. */
  errorLocation?: Pick<CommandSourceLocation, 'startLine' | 'endLine'> | null
  /** startLine -> number of steps generated by the statement on that line. */
  lineCommandCounts?: Map<number, number> | null
  /** Called when the user clicks a line (1-based). */
  onLineClick?: (lineNumber: number) => void
}

export function ProtocolCodeView({
  source,
  selectedLocation = null,
  errorLocation = null,
  lineCommandCounts = null,
  onLineClick,
}: ProtocolCodeViewProps): JSX.Element {
  const containerRef = useRef<HTMLDivElement>(null)
  const viewRef = useRef<EditorView | null>(null)
  const onLineClickRef = useRef(onLineClick)

  useEffect(() => {
    onLineClickRef.current = onLineClick
  }, [onLineClick])

  useEffect(() => {
    const container = containerRef.current
    if (container == null) return

    const counts = lineCommandCounts ?? new Map<number, number>()

    const view = new EditorView({
      parent: container,
      state: EditorState.create({
        doc: source,
        extensions: [
          lineNumbers(),
          gutter({
            class: 'cm-commandCountGutter',
            lineMarker: (view, block) => {
              const lineNumber = view.state.doc.lineAt(block.from).number
              const count = counts.get(lineNumber) ?? 0
              return count > 1 ? new CommandCountMarker(count) : null
            },
          }),
          python(),
          syntaxHighlighting(defaultHighlightStyle),
          highlightField,
          codeViewTheme,
          EditorState.readOnly.of(true),
          EditorView.editable.of(false),
          EditorView.domEventHandlers({
            click: (event, view) => {
              console.log('[ProtocolCodeView] click handler', {
                selEmpty: view.state.selection.main.empty,
                x: event.clientX,
                y: event.clientY,
              })
              // Let the user select/copy text without jumping steps: a click
              // that ends a text selection is ignored.
              if (!view.state.selection.main.empty) return false
              const pos = view.posAtCoords({
                x: event.clientX,
                y: event.clientY,
              })
              console.log('[ProtocolCodeView] pos', pos)
              if (pos == null) return false
              onLineClickRef.current?.(view.state.doc.lineAt(pos).number)
              return false
            },
          }),
        ],
      }),
    })
    viewRef.current = view

    return () => {
      view.destroy()
      viewRef.current = null
    }
  }, [source, lineCommandCounts])

  useEffect(() => {
    const view = viewRef.current
    if (view == null) return

    const specs: HighlightSpec[] = []
    if (errorLocation != null) {
      specs.push({ ...errorLocation, kind: 'error' })
    }
    if (selectedLocation != null) {
      specs.push({
        startLine: selectedLocation.startLine,
        endLine: selectedLocation.endLine,
        kind: 'selected',
      })
    }

    const effects: Array<StateEffect<unknown>> = [setHighlights.of(specs)]
    const scrollTarget = selectedLocation ?? errorLocation
    if (
      scrollTarget != null &&
      scrollTarget.startLine >= 1 &&
      scrollTarget.startLine <= view.state.doc.lines
    ) {
      effects.push(
        EditorView.scrollIntoView(
          view.state.doc.line(scrollTarget.startLine).from,
          { y: 'center' }
        )
      )
    }
    view.dispatch({ effects })
  }, [source, lineCommandCounts, selectedLocation, errorLocation])

  return <div ref={containerRef} className={styles.code_view} />
}
